# Generated by Django 5.1.1 on 2024-12-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="records",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("g", models.IntegerField()),
                ("b", models.IntegerField()),
                ("l", models.IntegerField()),
                ("r", models.IntegerField()),
                ("bl", models.IntegerField()),
                ("br", models.IntegerField()),
                ("blr", models.IntegerField()),
                ("blri", models.IntegerField()),
                ("msg", models.IntegerField()),
            ],
        ),
    ]
